### ISSUE TITLE
Module build failed: ReferenceError: define is not defined

### ISSUE THREAD

**Issue by ylavoie** [OpenNTF/dojo-webpack-plugin#167]
I am having problems making my bundle, every try ends with:

ERROR in ./js-src/dojo/domReady.js
Module build failed: ReferenceError: define is not defined
   at Object.<anonymous> (/srv/ledgersmb/UI/js-src/dojo/domReady.js:1:63)
   at Module._compile (/var/www/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
   at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
   at Module.load (internal/modules/cjs/loader.js:589:32)
   at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
   at Function.Module._load (internal/modules/cjs/loader.js:520:3)
   at Module.require (internal/modules/cjs/loader.js:626:17)
   at require (/var/www/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
   at loadLoader (/var/www/node_modules/loader-runner/lib/loadLoader.js:13:17)
   at iteratePitchingLoaders (/var/www/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
   at runLoaders (/var/www/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
   at NormalModule.doBuild (/var/www/node_modules/webpack/lib/NormalModule.js:235:3)
   at NormalModule.build (/var/www/node_modules/webpack/lib/NormalModule.js:365:15)
   at Compilation.buildModule (/var/www/node_modules/webpack/lib/Compilation.js:362:10)
   at factory.create (/var/www/node_modules/webpack/lib/Compilation.js:583:14)
   at factory (/var/www/node_modules/webpack/lib/NormalModuleFactory.js:366:6)
   at hooks.afterResolve.callAsync (/var/www/node_modules/webpack/lib/NormalModuleFactory.js:143:13)
   at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/var/www/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:42:1)
   at resolver (/var/www/node_modules/webpack/lib/NormalModuleFactory.js:126:29)
   at resolver (/var/www/node_modules/dojo-webpack-plugin/lib/DojoAMDModuleFactoryPlugin.js:198:5)
   at process.nextTick (/var/www/node_modules/webpack/lib/NormalModuleFactory.js:304:9)
   at process._tickCallback (internal/process/next_tick.js:61:11)
@ ./js-src/webpack/bootstrap.js 16:0-21:2

My application is a Perl app with a Dojo based UI. The directory structure is:

```
app
+----- UI
        +----- js (Compiled dojo)
        +----- node_modules ( there for the moment, should be elsewhere )
        +----- js-src (Sources)
                   +----- dojo
                   +----- dijit
                   +----- util
                   +----- lsmb (our specific UI modules)
                   +----- webpack (webpack specifics)
```
The UI is made available to the web with a `/js` url. I cloned dojo-webpack-plugin-sample, which ran perfectly well here, and adjusted a bit.

webpack version is 4.8.1,
node, 10.1.0
dojo, 1.11.5

The application builds and run fine with Dojo loader, I am trying to move it to webpack to be able to add a few React pages.

The only real difference I found is the directory structure.

Here are my config files:
[webpack.config.js.txt](https://github.com/OpenNTF/dojo-webpack-plugin/files/1991792/webpack.config.js.txt)
[loaderConfig.js.txt](https://github.com/OpenNTF/dojo-webpack-plugin/files/1991801/loaderConfig.js.txt)
[bootstrap.js.txt](https://github.com/OpenNTF/dojo-webpack-plugin/files/1991802/bootstrap.js.txt)

And the resulting log file
[webpack.log.txt](https://github.com/OpenNTF/dojo-webpack-plugin/files/1991809/webpack.log.txt)

**Comment by chuckdumont** [comment]
The problem is that your app is using the `dojo/domReady!` plugin and webpack is trying to load it as a webpack plugin.  Webpack cannot run dojo loader plugins directly, so you either need to replace `dojo/domReady` with `dojo/ready` or, if you don't want to (or can't) change the source, you can use the `dojo/loaderProxy` webpack plugin to proxy `dojo/domReady` as follows:

```javascript
      plugins: [
        new webpack.NormalModuleReplacementPlugin(
          // dojo/domReady (only works if the DOM is ready when invoked)
          /^dojo\/domReady!/, (data) => {
            const match = /^dojo\/domReady!(.*)$/.exec(data.request);
            data.request = "dojo/loaderProxy?loader=dojo/domReady!" + match[1];
          }
        ),
```
Note however that, as indicated by the comment, this **only** works if the DOM is ready when the module containing the `dojo/domReady` define dependency is loaded.  If the DOM is not ready, then a run-time exception will be throw.  That's because webpack does not allow module loaders to complete asynchronously.  That means that you still need to use `dojo/ready` (or some other means) to wait for the DOM to be ready **prior** to loading the offending module.  This can be useful for avoiding having to change third-party code that uses `dojo/domReady`, but if it is your own code, then the best approach is to remove `dojo/domReady` and use `dojo/ready` instead.

**Comment by chuckdumont** [comment]
Also, you should remove js-src from the resolveLoader modules so that webpack won't try to load any Dojo loader plugins as webpack loaders.

**Comment by chuckdumont** [comment]
Closing this due to lack of response.  If you are still having trouble, please reopen.

**Comment by chuckdumont** [comment]
Update.  dojo-webpack-plugin now supports the [async](https://github.com/OpenNTF/dojo-webpack-plugin#async) property in the configuration.  When this is true, then the dojo/domReady! can be used without the restriction that the DOM be ready when it is invoked, but note the caveats indicated in the documentation for this option.

**Comment by ylavoie** [comment]
With your comments here and your dojo-webpack-plugin-sample, I was able to make all my AMD modules using define work.
I'm still having issues with the ones which are using require instead of define.

**Comment by chuckdumont** [comment]
You'll need to provide more details.  What error are you seeing and what does the code that's failing look like.

**Comment by chuckdumont** [comment]
Update: starting with version 2.8, the [async](https://github.com/OpenNTF/dojo-webpack-plugin#async) option can be used to allow Dojo loader extensions to complete asynchronously.
