### ISSUE TITLE
Build fails with Webpack 4.19.1

### ISSUE THREAD

**Issue by agavrilov** [OpenNTF/dojo-webpack-plugin#180]
The build fails with Webpack 4.19.1. The stack trace below. The issue can be seen [here](https://github.com/agavrilov/dojo-webpack-plugin-sample/tree/webpack-4.19.1). Just run 'npm install' and 'npm run build'.

I think this issue is caused by the refactoring of 'webpack-sources' code. It changed the representation of replacements. See the relevant commit [here](https://github.com/webpack/webpack-sources/commit/603578164f3e6e176530a47c1ab07f692e3db351).

The stack trace:
<pre>
ERROR in chunk main [entry]
bundle.js
C:\P\git\dojo-webpack-plugin-sample\node_modules\dojo\_base\lang.js
Cannot read property 'replace' of undefined
TypeError: C:\P\git\dojo-webpack-plugin-sample\node_modules\dojo\_base\lang.js
Cannot read property 'replace' of undefined
    at source.replacements.forEach (C:\P\git\dojo-webpack-plugin-sample\node_modules\dojo-webpack-plugin\lib\DojoAMDDefineDependency.js:36:37)
    at Array.forEach (<anonymous>)
    at DojoAMDDefineDependencyTemplate.fixupDefineScope (C:\P\git\dojo-webpack-plugin-sample\node_modules\dojo-webpack-plugin\lib\DojoAMDDefineDependency.js:35:24)
    at DojoAMDDefineDependencyTemplate.apply (C:\P\git\dojo-webpack-plugin-sample\node_modules\dojo-webpack-plugin\lib\DojoAMDDefineDependency.js:30:8)
    at JavascriptGenerator.sourceDependency (C:\P\git\dojo-webpack-plugin-sample\node_modules\webpack\lib\JavascriptGenerator.js:151:12)
    at JavascriptGenerator.sourceBlock (C:\P\git\dojo-webpack-plugin-sample\node_modules\webpack\lib\JavascriptGenerator.js:44:9)
    at JavascriptGenerator.generate (C:\P\git\dojo-webpack-plugin-sample\node_modules\webpack\lib\JavascriptGenerator.js:23:8)
    at NormalModule.source (C:\P\git\dojo-webpack-plugin-sample\node_modules\webpack\lib\NormalModule.js:485:33)
    at ModuleTemplate.render (C:\P\git\dojo-webpack-plugin-sample\node_modules\webpack\lib\ModuleTemplate.js:54:32)
    at modules.map.module (C:\P\git\dojo-webpack-plugin-sample\node_modules\webpack\lib\Template.js:233:28)
    at Array.map (<anonymous>)
    at Function.renderChunkModules (C:\P\git\dojo-webpack-plugin-sample\node_modules\webpack\lib\Template.js:230:30)
    at compilation.mainTemplate.hooks.modules.tap (C:\P\git\dojo-webpack-plugin-sample\node_modules\webpack\lib\JavascriptModulesPlugin.js:86:23)
    at SyncWaterfallHook.eval [as call] (eval at create (C:\P\git\dojo-webpack-plugin-sample\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:16)
    at SyncWaterfallHook.lazyCompileHook (C:\P\git\dojo-webpack-plugin-sample\node_modules\tapable\lib\Hook.js:154:20)
    at MainTemplate.hooks.render.tap (C:\P\git\dojo-webpack-plugin-sample\node_modules\webpack\lib\MainTemplate.js:160:25)
    at SyncWaterfallHook.eval [as call] (eval at create (C:\P\git\dojo-webpack-plugin-sample\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:16)
    at SyncWaterfallHook.lazyCompileHook (C:\P\git\dojo-webpack-plugin-sample\node_modules\tapable\lib\Hook.js:154:20)
    at MainTemplate.render (C:\P\git\dojo-webpack-plugin-sample\node_modules\webpack\lib\MainTemplate.js:412:34)
    at Object.render (C:\P\git\dojo-webpack-plugin-sample\node_modules\webpack\lib\JavascriptModulesPlugin.js:65:34)
    at Compilation.createChunkAssets (C:\P\git\dojo-webpack-plugin-sample\node_modules\webpack\lib\Compilation.js:2364:29)
    at hooks.optimizeTree.callAsync.err (C:\P\git\dojo-webpack-plugin-sample\node_modules\webpack\lib\Compilation.js:1269:10)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\P\git\dojo-webpack-plugin-sample\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (C:\P\git\dojo-webpack-plugin-sample\node_modules\tapable\lib\Hook.js:154:20)
    at Compilation.seal (C:\P\git\dojo-webpack-plugin-sample\node_modules\webpack\lib\Compilation.js:1214:27)
    at hooks.make.callAsync.err (C:\P\git\dojo-webpack-plugin-sample\node_modules\webpack\lib\Compiler.js:547:17)
    at _done (eval at create (C:\P\git\dojo-webpack-plugin-sample\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:9:1)
    at _err1 (eval at create (C:\P\git\dojo-webpack-plugin-sample\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:32:22)
    at _addModuleChain (C:\P\git\dojo-webpack-plugin-sample\node_modules\webpack\lib\Compilation.js:1065:12)
    at processModuleDependencies.err (C:\P\git\dojo-webpack-plugin-sample\node_modules\webpack\lib\Compilation.js:981:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
</pre>

**Comment by chuckdumont** [comment]
Thanks for the bug report. Please try version 2.7.6-0.

**Comment by ryangroth5** [comment]
```> @ development /opt/americanwhitewater.org
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=webpack.dev.config.js

/opt/americanwhitewater.org/node_modules/webpack-cli/bin/webpack.js:449
                                throw err;
                                ^

Error: No hook for resolver normal in object ResolverFactory
    at names.forEach.name (/opt/americanwhitewater.org/node_modules/webpack-plugin-compat/lib/pluginCompatV4.js:101:11)
    at Array.forEach (<anonymous>)
    at events.forEach.event (/opt/americanwhitewater.org/node_modules/webpack-plugin-compat/lib/pluginCompatV4.js:98:9)
    at Array.forEach (<anonymous>)
    at Object.tap (/opt/americanwhitewater.org/node_modules/webpack-plugin-compat/lib/pluginCompatV4.js:93:9)
    at DojoAMDResolverPluginV4.apply (/opt/americanwhitewater.org/node_modules/dojo-webpack-plugin/lib/DojoAMDResolverPluginV4.js:28:3)
    at applyResolverPlugin (/opt/americanwhitewater.org/node_modules/dojo-webpack-plugin/lib/compat.js:70:39)
    at DojoAMDPlugin.apply (/opt/americanwhitewater.org/node_modules/dojo-webpack-plugin/lib/DojoAMDPlugin.js:48:3)
    at webpack (/opt/americanwhitewater.org/node_modules/webpack/lib/webpack.js:37:12)
    at processOptions (/opt/americanwhitewater.org/node_modules/webpack-cli/bin/webpack.js:437:16)
    at yargs.parse (/opt/americanwhitewater.org/node_modules/webpack-cli/bin/webpack.js:513:3)
    at Object.parse (/opt/americanwhitewater.org/node_modules/webpack-cli/node_modules/yargs/yargs.js:552:18)
    at /opt/americanwhitewater.org/node_modules/webpack-cli/bin/webpack.js:218:8
    at Object.<anonymous> (/opt/americanwhitewater.org/node_modules/webpack-cli/bin/webpack.js:515:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/opt/americanwhitewater.org/node_modules/webpack/bin/webpack.js:155:2)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:696:3)

**Comment by agavrilov** [comment]
@chuckdumont Your fix works for me. Thanks!
@ryangroth5 It happens for me from time to time. Deleting 'node_modules' directory and reinstalling all modules usually fixes it for me

**Comment by chuckdumont** [comment]
I encountered this problem when I initially tried to update the sample application by simply changing the versions of webpack and dojo-webpack-plugin in package.json and running `npm install`.  Deleting the `node_modules` directory and `package-lock.json` and then re-running `npm install` resolved the problem.  It appears to be caused by a peer dependency not being updated properly.

**Comment by chuckdumont** [comment]
Version 2.7.6 is now available on npm

**Comment by chuckdumont** [comment]
More info on this.  The problem occurs when webapck and dojo-webpack-plugin (via the webpack-plugin-compat package) aren't using the same version of the tapable package.  This situation can occur in some upgrade scenarios.  As mentioned above, the easiest resolution is to delete node_modules and package-lock.json and run `npm install`.  However, if for some reason you don't want to delete your package-lock.json, you can resolve the issue by editing the file and manually hoisting the most recent version of tapable to the root and then removing the package specific instances.  `npm update` is supposed to be able to do this for you, but I've had limited success with it.
