### ISSUE TITLE
Error with Webpack >=4.18.1: "No hook for resolver normal in object ResolverFactory"

### ISSUE THREAD

**Issue by pshendry** [OpenNTF/dojo-webpack-plugin#184]
I'm getting an error on build after upgrading from webpack `4.16.2` to `4.23.0`. After narrowing it down, it appears that `4.18.0` is the last version that's working for me, and `4.18.1` is the first version where it breaks. I do not envy you guys for using an API that breaks on a patch-version release...

Build error:

```
> webpack --progress --watch --info-verbosity verbose --mode=development --env.NODE_ENV=development --config build/webpack.config.js


D:\Code\RC-Reporter\ReporterClient\node_modules\webpack-plugin-compat\lib\pluginCompatV4.js:101
                                throw new Error(`No hook for ${name} in object ${obj.constructor.name}`);
          ^
Error: No hook for resolver normal in object ResolverFactory
    at names.forEach.name (D:\Code\RC-Reporter\ReporterClient\node_modules\webpack-plugin-compat\lib\pluginCompatV4.js:101:11)
    at Array.forEach (<anonymous>)
    at events.forEach.event (D:\Code\RC-Reporter\ReporterClient\node_modules\webpack-plugin-compat\lib\pluginCompatV4.js:98:9)
    at Array.forEach (<anonymous>)
    at Object.tap (D:\Code\RC-Reporter\ReporterClient\node_modules\webpack-plugin-compat\lib\pluginCompatV4.js:93:9)
    at DojoAMDResolverPluginV4.apply (D:\Code\RC-Reporter\ReporterClient\node_modules\dojo-webpack-plugin\lib\DojoAMDResolverPluginV4.js:28:3)
    at applyResolverPlugin (D:\Code\RC-Reporter\ReporterClient\node_modules\dojo-webpack-plugin\lib\compat.js:70:39)
    at DojoAMDPlugin.apply (D:\Code\RC-Reporter\ReporterClient\node_modules\dojo-webpack-plugin\lib\DojoAMDPlugin.js:48:3)
    at webpack (D:\Code\RC-Reporter\ReporterClient\node_modules\webpack\lib\webpack.js:47:13)
    at processOptions (D:\Code\RC-Reporter\ReporterClient\node_modules\webpack-cli\bin\cli.js:441:16)
    at yargs.parse (D:\Code\RC-Reporter\ReporterClient\node_modules\webpack-cli\bin\cli.js:536:3)
    at Object.parse (D:\Code\RC-Reporter\ReporterClient\node_modules\webpack-cli\node_modules\yargs\yargs.js:563:18)
    at D:\Code\RC-Reporter\ReporterClient\node_modules\webpack-cli\bin\cli.js:219:8
    at Object.<anonymous> (D:\Code\RC-Reporter\ReporterClient\node_modules\webpack-cli\bin\cli.js:538:3)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Code\RC-Reporter\ReporterClient\node_modules\webpack\bin\webpack.js:155:2)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

Dojo loader config:

```
{
        baseUrl: env.dojoRoot,
        blankGif: '/rcr-src/dist/images/blank.gif',
        extraLocale: ['en-us'],
        isDebug: env.isDebug,
        packages: [
            { name: 'dgrid', location: env.dojoRoot + '/RCDGrid/dgrid', lib: '.' },
            { name: 'dijit', location: env.dojoRoot + '/DojoToolkit/dijit', lib: '.' },
            { name: 'dojo', location: env.dojoRoot + '/DojoToolkit/dojo', lib: '.' },
            { name: 'dojox', location: env.dojoRoot + '/DojoToolkit/dojox', lib: '.' },
            { name: 'put-selector', location: env.dojoRoot + '/RCDGrid/put-selector', lib: '.' },
            { name: 'rc', location: env.dojoRoot + '/rc', lib: '.' },
            { name: 'xstyle', location: env.dojoRoot + '/RCDGrid/xstyle', lib: '.' },
            { name: 'FusionCharts', location: env.dojoRoot + '/FusionCharts', lib: '.'}
        ],
    };
```

Webpack plugin config:

```
            new DojoWebpackPlugin({
                // The Dojo loader configuration. By importing it instead of defining it inline, we can use the
                // `environment` and `buildEnvironment` options below to alter the loader config at run-time vs at
                // build-time.
                loaderConfig: require("./dojoLoaderConfig"),
                environment: { dojoRoot: "/rcr-src", isDebug },
                buildEnvironment: { dojoRoot: legacyRoot, isDebug },
                noConsole: true,
            }),
```

**Comment by chuckdumont** [comment]
What version of dojo-webpack-plugin are you using?  This sounds similar to https://github.com/OpenNTF/dojo-webpack-plugin/issues/180.

**Comment by pshendry** [comment]
Oops, bit of an important detail; I'm on dojo-webpack-plugin v2.7.6, the latest. I'll have a go at making a test case.

**Comment by chuckdumont** [comment]
Please try the workaround mentioned in #180 first (i.e. delete node_modules and package-lock.json)

**Comment by pshendry** [comment]
The workaround fixed it, thanks and sorry for missing that closed issue!

**Comment by chuckdumont** [comment]
See https://github.com/OpenNTF/dojo-webpack-plugin/issues/180#issuecomment-502093579 for more details on this issue.
