### ISSUE TITLE
Error when using plugin

### ISSUE THREAD

**Issue by KlausSchaefers** [OpenNTF/dojo-webpack-plugin#199]
Hi, 

I get the following error when trying to use the loader:

Error: No hook for resolver normal in object ResolverFactory
    at names.forEach.name (/Users/Klaus/git/matc_ui/node_modules/webpack-plugin-compat/lib/pluginCompatV4.js:101:11)
    at Array.forEach (<anonymous>)
    at events.forEach.event (/Users/Klaus/git/matc_ui/node_modules/webpack-plugin-compat/lib/pluginCompatV4.js:98:9)
    at Array.forEach (<anonymous>)
    at Object.tap (/Users/Klaus/git/matc_ui/node_modules/webpack-plugin-compat/lib/pluginCompatV4.js:93:9)
    at DojoAMDResolverPluginV4.apply (/Users/Klaus/git/matc_ui/node_modules/dojo-webpack-plugin/lib/DojoAMDResolverPluginV4.js:28:3)
    at applyResolverPlugin (/Users/Klaus/git/matc_ui/node_modules/dojo-webpack-plugin/lib/compat.js:70:39)
    at DojoAMDPlugin.apply (/Users/Klaus/git/matc_ui/node_modules/dojo-webpack-plugin/lib/DojoAMDPlugin.js:48:3)
    at webpack (/Users/Klaus/git/matc_ui/node_modules/webpack/lib/webpack.js:47:13)
    at processOptions (/Users/Klaus/git/matc_ui/node_modules/webpack-cli/bin/cli.js:441:16)
    at yargs.parse (/Users/Klaus/git/matc_ui/node_modules/webpack-cli/bin/cli.js:536:3)
    at Object.parse (/Users/Klaus/git/matc_ui/node_modules/yargs/yargs.js:567:18)
    at /Users/Klaus/git/matc_ui/node_modules/webpack-cli/bin/cli.js:219:8
    at Object.<anonymous> (/Users/Klaus/git/matc_ui/node_modules/webpack-cli/bin/cli.js:538:3)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/Klaus/git/matc_ui/node_modules/webpack/bin/webpack.js:155:2)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! expack@1.0.0 buildDev: `rm -rf dist && webpack --mode development --config webpack.server.config.js && webpack --mode development --config webpack.dev.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the expack@1.0.0 buildDev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by chuckdumont** [comment]
Not sure.  Can you provide a test case that reproduces the problem?

**Comment by KlausSchaefers** [comment]
Hi,

It seems this was a version error. I set webpack to 4.2.0  and everything seems to work.

**Comment by chuckdumont** [comment]
@KlausSchaefers, what version of webpack were you seeing the problem with?

**Comment by KlausSchaefers** [comment]
Hi, I was using 4.28.3. Now that it runs I run into another issue. I am try to use th eplugin with the dev-middleware. I get the following errors:

```
ERROR in ./src/de/vommond/matc/App.js
Module not found: Error: Can't resolve 'de/vommond/Dialog' in '/Users/Klaus/git/matc_ui/src/de/vommond/matc'
 @ ./src/de/vommond/matc/App.js 5:0-640:2
 @ ./src/index.js
 @ multi webpack-hot-middleware/client?path=/__webpack_hmr&timeout=20000 ./src/index.js /var/folders/gj/6nsk1_k900gctg6vqzh_dcq00000gn/T/tmp-9034Kr0FihHcmyNz/dojo/dojo.js
```

The de/vommond/App imports the de/vommon/Dialog with a standard dojo require. But it looks to me that the loader is not resolving the package correctly. My guess is, that the dojo loader is somehow not active, is that possible?

**Comment by chuckdumont** [comment]
4.28.3 should be fine.  I just built the sample app using 4.28.3 without any issues.  Could you try deleting your node_modules directory and then running `npm install` to see if that clears up the problem?

**Comment by KlausSchaefers** [comment]
No, I get the same error...

**Comment by chuckdumont** [comment]
@KlausSchaefers, you problem sounds a lot like [this issue](https://github.com/OpenNTF/dojo-webpack-plugin/issues/184).  Please make sure you are using the latest versions of webpack and dojo-webpack-plugin and delete your node_modules directory and your package-lock.json.  Then run `npm install` and try rebuilding again.

If that doesn't resolve your problem, please provide a test case that reproduces the issue.  Thanks.

**Comment by chuckdumont** [comment]
Closing due to lack of response.
