### ISSUE TITLE
Bundling Error while loading JSON with dojo/text

### ISSUE THREAD

**Issue by vaxul** [OpenNTF/dojo-webpack-plugin#256]
Hi,

I'm stuck with the following error while bundling, wenn I try to load a JSON file with `dojo/text`:
```
ERROR in ./source/json/config.json (./node_modules/dojo-webpack-plugin/loaders/dojo/text!./source/json/config.json)
Module parse failed: Unexpected token m in JSON at position 0 while parsing near 'module.exports = "{\...'
File was processed with these loaders:
 * ./node_modules/dojo-webpack-plugin/loaders/dojo/text/index.js
You may need an additional loader to handle the result of these loaders.
SyntaxError: Unexpected token m in JSON at position 0 while parsing near 'module.exports = "{\...'
    at JSON.parse (<anonymous>)
    at parseJson (C:\example\build\node_modules\json-parse-better-errors\index.js:7:17)
    at JsonParser.parse (C:\example\build\node_modules\webpack\lib\JsonParser.js:16:16)
    at doBuild.err (C:\example\build\node_modules\webpack\lib\NormalModule.js:482:32)
    at runLoaders (C:\example\build\node_modules\webpack\lib\NormalModule.js:358:12)
    at C:\example\build\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\example\build\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\example\build\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at C:\example\build\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at runSyncOrAsync (C:\example\build\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (C:\example\build\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (C:\example\build\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\example\build\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:43:16)
    at provider (C:\example\build\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:79:9)
    at C:\example\build\node_modules\graceful-fs\graceful-fs.js:115:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
 @ ./source/js/mockup/config.js 
```

I'm not sure what the message "You may need an additional loader to handle the result of these loaders." should tell me.
Webpack-Loader, Dojo-Loader or something other?

This is the basic module for fetching the JSON:
```js
define([
  'dojo/json',
  'dojo/text!json/config.json',
], function(JSON, configJson) {

// ...
// console.log(JSON.parse(configJson, true))
// ...

});
```
Note: The JSON.parse is commented out.

As far as I understand the loader `dojo-webpack-plugin/loaders/dojo/text` return an `module.export`  which webpack tries to parse, which fails.

Does something went wrong or do I do something wrong?

**Comment by chuckdumont** [comment]
Try adding the following in your webpack.config.js:

```javascript
  module: {
    rules: [
      //...
      {
        test: /\.json$/,
        type: 'javascript/auto'
      }
    ]
  }
```

This tells webpack to skip it's automatic parsing of JSON files.

**Comment by vaxul** [comment]
@chuckdumont 
Thank you for your quick response. This helped.
