### ISSUE TITLE
Build error when using ExtractTextPlugin

### ISSUE THREAD

**Issue by ylavoie** [OpenNTF/dojo-webpack-plugin#282]
I am facing a problem similar as #23 while trying to use babel, jshint or eslint. Any one of those is using a loader and gives:

```
/var/www/node_modules/dojo-webpack-plugin/lib/DojoLoaderPlugin.js:238
                                        throw Error("Can't locate " + options.loader + " in compilation");
                                        ^
Error: Can't locate /tmp/tmp-48XKf8MzukF3JS/dojo/dojo.js in compilation
    at /var/www/node_modules/dojo-webpack-plugin/lib/DojoLoaderPlugin.js:238:12
    at Array.forEach (<anonymous>)
    at DojoLoaderPlugin.afterOptimizeChunks (/var/www/node_modules/dojo-webpack-plugin/lib/DojoLoaderPlugin.js:235:10)
    at SyncHook.eval [as call] (eval at create (/var/www/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:5:1)
    at SyncHook.lazyCompileHook (/var/www/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.seal (/var/www/node_modules/webpack/lib/Compilation.js:1340:34)
    at /var/www/node_modules/webpack/lib/Compiler.js:675:18
    at /var/www/node_modules/webpack/lib/Compilation.js:1261:4
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/www/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at AsyncSeriesHook.lazyCompileHook (/var/www/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/var/www/node_modules/webpack/lib/Compilation.js:1253:28)
    at /var/www/node_modules/webpack/lib/Compiler.js:672:17
    at _done (eval at create (/var/www/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at eval (eval at create (/var/www/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:42:22)
    at /var/www/node_modules/webpack/lib/Compilation.js:1185:12
    at /var/www/node_modules/webpack/lib/Compilation.js:1097:9
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```
webpack.config.js has:
```
    module: {
      rules: [{
        test: /.js/,
        enforce: 'pre',
        exclude: /node_modules/,
        use: [
          {
            loader: `jshint-loader`,
            options: {emitErrors: true}
          }
        ]
      },
    ]},
```
dojo-webpack-plugin is 2.8.13 and webpack is 4.42.1

Amy specific configuration or requirement in using a loader?

**Comment by chuckdumont** [comment]
Could you provide a test case that reproduces the problem?

**Comment by ylavoie** [comment]
Fixed. resolveLoader was pointing only to my modules and wasn't including 'node_modules'
I'm trying to set a test case using `dojo-webpack-plugin-sample` to reproduce the problem but it keep working and reporting properly about a missing loader instead of crashing.

**Comment by chuckdumont** [comment]
So I'm confused.  Do you still have an issue or are you all set?

**Comment by ylavoie** [comment]
I managed to get it working by adding 'node_modules' to 'resolveLoader', so I good.

Nevertheless, the plugin should detect that it cannot find a specific loader in the provided list and give a proper error message instead of the crash report shown above.

**Comment by chuckdumont** [comment]
I suppose.  But that's a webpack issue.  dojo-webpack-plugin doesn't have anything to  do with loader module resolution, except for when it comes to Dojo loaders plugins.
