### ISSUE TITLE
Dojo code in html files

### ISSUE THREAD

**Issue by ylavoie** [OpenNTF/dojo-webpack-plugin#283]
I'm trying to figure out how to make the plugin consider some html files to discover all dependencies.

We have many html files which are using inline scripts like this:
```
<script type="text/javascript">
  require(['dojo/dom', 'dojo/dom-style', 'dojo/ready'],
  function(dom, style, ready) {
    ready(80, function() {
  style.set(dom.byId('loading'), 'display', 'none');
  });
  });
</script>
```
Running the webpacked application result in undefined references and maintaining the dependencies manually will be a maintenance burden. See this for example:
```
'use strict'

const DojoWebpackPlugin = require("dojo-webpack-plugin");
const HtmlWebpackPlugin = require('html-webpack-plugin');

const path = require("path");
const webpack = require("webpack");

module.exports = env => {
  const devMode = process.env.NODE_ENV !== 'production';
  return {
    context: path.join(__dirname, "UI"),
    entry: {
      'login': 'lsmb/login',
      'lib': [
        'dojo/dom',
        'dojo/dom-style',
        'dojo/ready',
        'dojo/on',
        'dijit/Dialog',                 // main.html, login
        'dijit/Tooltip',                // elements.html, user.html, elements.html, new_user.html
        'dijit/form/ComboBox',          // setup, Is_LSMB_running
        'dijit/form/CurrencyTextBox',   // elements.html
        'dijit/form/MultiSelect',       // elements.html
        'dijit/form/NumberSpinner',     // balance_sheet, income_statement
        'dijit/layout/BorderContainer', // main.html
        'dijit/layout/TabContainer',    // edit.html, yearend.html, contact.html
      ]
    },

    output: {
      path: path.join(__dirname, "UI/js"),  // js path
      publicPath: 'js/',                    // images path
      pathinfo: devMode ? true : false,     // keep source references?
      filename: '[name].js',
      chunkFilename: '[name].[chunkhash].js'
    },

    module: {
      rules: [{
        test: /\.html$/,
        use: 'html-loader'
      }
    ]},

    plugins: [
      new HtmlWebpackPlugin({
        template: './login.html',
        inject: 'body',
        chunks: ['lib','login'],
        filename: 'login.html'
      }),

      new DojoWebpackPlugin({
        loaderConfig: require("./UI/js-src/webpack/loaderConfig.js"),
        environment: {dojoRoot: "js"},    // used at run time for non-packed resources (e.g. blank.gif)
        buildEnvironment: {dojoRoot: "js-src"}, // used at build time
        locales: ["en"],
        async: true,
        noConsole: true
      }),
    ],
    mode: devMode ? 'development' : 'production',
  };
};
```

**Comment by chuckdumont** [comment]
I would expect calling global require from your html files to work as long as the webpack bundle containing the runtime code has been loaded and all the required dependencies are included.

I don't know of any plugin that will scan html files for require dependencies, though.

**Comment by ylavoie** [comment]
`web-webpack-plugin.AutoWebPlugin` does scan a directory for html and adds them as entry points.
But it flushes all entries and imposes the html it found, so no dojo.

**Comment by ylavoie** [comment]
I'm trying to load this small html example:
```
<body id="setup-login" class="lsmb">
    <div class="setupconsole" style="position:relative;height:100%">
        <div id="loading">
            <img style="display: block; margin: auto auto;"
                 src="js/dijit/icons/images/loadingAnimation.gif"
                 alt="If this text is showing, there's most likely a problem with the Dojo setup"
                 title="Loading ..."
                 width="20" height="20" />
        </div>
        <div id="logindiv">
            <div class="login" align="center">
                <a href="http://www.ledgersmb.org/"
                   target="_top">
                   <img src="images/ledgersmb.png"
                        class="logo"
                        alt="LedgerSMB Logo" />
                </a>
            </div>
        </div>
    </div>
    <script>
      require(['dojo/dom', 'dojo/dom-style', 'dojo/ready'],
      function(dom, style, ready) {
        ready(80, function() {
            style.set(dom.byId('loading'), 'display', 'none');
        });
      });
    </script>
</body>
</html>
```
The directory structure looks like:
```
UI/setup/test.html

UI/images/:
down.gif       ledgersmb.gif  ledgersmb_small-trans.png  logo.eps  logo_small.png
ledgersmb.eps  ledgersmb.png  ledgersmb_small.png        logo.png  up.gif
```
And the project context is set to `UI/`

Compiling the project gives:
```
    ERROR in ./setup/test.html (/var/www/node_modules/html-webpack-plugin/lib/loader.js!./setup/test.html)
    Module not found: Error: Can't resolve './images/ledgersmb.png' in '/srv/ledgersmb/UI/setup'
    resolve './images/ledgersmb.png' in '/srv/ledgersmb/UI/setup'
      using description file: /srv/ledgersmb/package.json (relative path: ./UI/setup)
        Field 'browser' doesn't contain a valid alias configuration
        using description file: /srv/ledgersmb/package.json (relative path: ./UI/setup/images/ledgersmb.png)
          no extension
            /srv/ledgersmb/UI/setup/images/ledgersmb.png doesn't exist
          .js
            /srv/ledgersmb/UI/setup/images/ledgersmb.png.js doesn't exist
          as directory
            /srv/ledgersmb/UI/setup/images/ledgersmb.png doesn't exist
    [/srv/ledgersmb/UI/setup/images/ledgersmb.png]
    [/srv/ledgersmb/UI/setup/images/ledgersmb.png.js]
     @ ./setup/test.html (/var/www/node_modules/html-webpack-plugin/lib/loader.js!./setup/test.html) 4:33-66
```

The relative path asked was `images/ledgersmb.png` which refers to the directory of the project, why was it remapped to the location of the source?

**Comment by ylavoie** [comment]
I managed to load all my html files one by one with `html-webpack-plugin`
The simple one shown above generates:
```
  Module build failed (from /var/www/node_modules/dojo-webpack-plugin/loaders/do  jo/loaderProxy/index.js):
  Error: No hook for get dojo require in object Compiler
  - pluginCompatV4.js:124 callHook
    [www]/[webpack-plugin-compat]/lib/pluginCompatV4.js:124:9
  - pluginCompatV4.js:143 callSyncBail
    [www]/[webpack-plugin-compat]/lib/pluginCompatV4.js:143:10
  - Error: No hook for get dojo require in object Compiler
  - Module parse failed: No hook for get dojo require in object Compiler
  - You may need an appropriate loader to handle this file type, currently no lo    aders are configured to process this file. See https://webpack.js.org/concep    ts#loaders
  - Error: No hook for get dojo require in object Compiler
```
So it seems obvious that the html files need to go through `html-loader` and a dojo equivalent to parse the embedded scripts. How can I assign them?

The relevant portion of my `webpack.config.fs` is:
```
    module: {
      rules: [{
        test: /\.html$/,
        loader: 'html-loader'
      }
    ]},

    plugins: [
      new DojoWebpackPlugin({
        loaderConfig: require("./UI/js-src/webpack/loaderConfig.js"),
        environment: {dojoRoot: "js"},    // used at run time for non-packed resources (e.g. blank.gif)
        buildEnvironment: {dojoRoot: "js-src"}, // used at build time
        locales: ["en"],
        async: true,
        noConsole: true
      }),
      new HtmlWebpackPlugin({ template: 'Test.html', filename: 'Test' }),
    ],
```

**Comment by chuckdumont** [comment]
I modified the sample application as shown in this [pull request](https://github.com/OpenNTF/dojo-webpack-plugin-sample/pull/83) and it works just fine.  Not sure what you're trying to do with html-loader, but I don't think you need it.

**Comment by ylavoie** [comment]
I hope I don't need it. The simpler, the better.

My only question is how do I find all dojo dependencies of those 128 modules without searching them by hand and placing manually into a bootstrap module?

If all html files are loaded at compile time, then dependencies will be resolved automatically.

**Comment by chuckdumont** [comment]
I don't know how to do that.  The best advice I can offer is to refactor the code so that each of the html files requires at most one javascript file that defines the dependencies for that html file.  So if the html file in your example is called index1.htm, then it would do:

```
<script type="text/javascript">
  require(['index1'], function(index1) {
    index1.go();
  });
</script>
```
and index1.js would specify the dependencies and perform the page specific action:
```
 define(['dojo/dom', 'dojo/dom-style', 'dojo/ready'],
  function(dom, style, ready) {
    return {
      go: function() {
        ready(80, function() {
          style.set(dom.byId('loading'), 'display', 'none');
        });
     };
  }
);
```
Then, in your bootstrap module, include each of the dep modules as dependencies:
```
define([index1, index2, index3, ...],
```
This doesn't save you the effort you were looking to avoid, but it does make it easier to manage the dependencies for your code in the future.

**Comment by ylavoie** [comment]
I was hoping I could load all html files and set a rule to use `html-loader` and a `dojo-loader` to grab the dependencies.

Finding the list of html files and adding them as entry points is done.

Now, how does the plugin finds the JS files?

**Comment by chuckdumont** [comment]
Webpack finds JavaScript dependencies by statically analyzing all your CommonJS and AMD module dependencies starting with the entry modules.

**Comment by ylavoie** [comment]
> I modified the sample application as shown in this [pull request](https://github.com/OpenNTF/dojo-webpack-plugin-sample/pull/83) and it works just fine. Not sure what you're trying to do with html-loader, but I don't think you need it.

According to dojo documentation, dojo/query and dojo/domQuery! are equivalent. This simple PR on the sample application crashes.
```
diff --git a/js/bootstrap.js b/js/bootstrap.js
index 63d7d91..5ed6409 100644
--- a/js/bootstrap.js
+++ b/js/bootstrap.js
@@ -14,14 +14,14 @@
  * limitations under the License.
  */
 define([
-       "dojo/ready",
        "dojo/parser",
        "dijit/layout/TabContainer",
        "js/LazyContentPane",
        "dojo/has!webpack?dojo-webpack-plugin/amd/dojoES6Promise",
        "css!dijit/themes/claro/claro.css",
-       "css!theme/sample.less"
-], function(ready, parser) {
+       "css!theme/sample.less",^M
+       "dojo/domReady!"^M
+], function(parser) {^M
        ready(function() {
                parser.parse();
        });
```
Results in:
```
Entrypoint main = bundle.js bundle.js.map
 [95] ./js/bootstrap.js 953 bytes {0} [built]
[138] ./js/LazyContentPane.js 2.8 KiB {0} [built]
[226] ./node_modules/style-loader!./node_modules/css-loader!./node_modules/less-loader/dist/cjs.js!./theme/sample.less 1.17 KiB {0} [built]
[227] ./node_modules/css-loader!./node_modules/less-loader/dist/cjs.js!./theme/sample.less 1.45 KiB {0} [built]
[228] ./node_modules/dojo/domReady.js 2.16 KiB {0} [not cacheable] [built] [failed] [1 error]
[229] /tmp/tmp-7TwRHvYPHqd2a/dojo/dojo.js 67.5 KiB {0} [built]
    + 325 hidden modules

ERROR in ./node_modules/dojo/domReady.js
Module build failed (from ./node_modules/dojo/domReady.js):
ReferenceError: define is not defined
    at Object.<anonymous> (/home/node/node_modules/dojo/domReady.js:1:63)
    at Module._compile (/home/node/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (/home/node/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at loadLoader (/home/node/node_modules/loader-runner/lib/loadLoader.js:18:17)
    at iteratePitchingLoaders (/home/node/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/home/node/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
    at NormalModule.doBuild (/home/node/node_modules/webpack/lib/NormalModule.js:280:3)
    at NormalModule.build (/home/node/node_modules/webpack/lib/NormalModule.js:427:15)
    at Compilation.buildModule (/home/node/node_modules/webpack/lib/Compilation.js:635:10)
    at /home/node/node_modules/webpack/lib/Compilation.js:884:14
    at /home/node/node_modules/webpack/lib/NormalModuleFactory.js:405:6
    at /home/node/node_modules/webpack/lib/NormalModuleFactory.js:155:13
    at _next0 (eval at create (/home/node/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:67:1)
    at eval (eval at create (/home/node/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:82:1)
    at DojoAMDModuleFactoryPlugin.afterResolve (/home/node/node_modules/dojo-webpack-plugin/lib/DojoAMDModuleFactoryPlugin.js:306:3)
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/home/node/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:75:1)
    at /home/node/node_modules/webpack/lib/NormalModuleFactory.js:138:29
    at /home/node/node_modules/dojo-webpack-plugin/lib/DojoAMDModuleFactoryPlugin.js:325:5
    at /home/node/node_modules/webpack/lib/NormalModuleFactory.js:342:9
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
 @ ./js/bootstrap.js 16:0-29:2
```

**Comment by chuckdumont** [comment]
`dojo/ready` and `dojo/domReady` are not equivalent.  The are used for the same purpose, but `domReady` is a dojo loader extension and `ready` is not.  Dojo loader extensions cannot be used in webpack without the use of [dojo/loaderProxy](https://github.com/OpenNTF/dojo-webpack-plugin#the-dojoloaderproxy-loader-extension).  See #167 for an example of how to use `dojo/domReady`.  Note that you will also need to enable the [async option](https://github.com/OpenNTF/dojo-webpack-plugin#async) if you need `dojo/domReady` to resolve asynchronously.  Pay attention to the caveats associated with the async option if applicable.

**Comment by chuckdumont** [comment]
@ylavoie - are you all set?  Can this issue be closed?

**Comment by ylavoie** [comment]
It sure can. Thanks for your help
