### ISSUE TITLE
Webpack 5 support

### ISSUE THREAD

**Issue by fkranenburg** [OpenNTF/dojo-webpack-plugin#314]
After upgrading to Webpack 5 we receive this stacktrace.

```
[webpack-cli] Promise rejection: Error: Cannot find module 'webpack/lib/dependencies/WebpackMissingModule'
Require stack:
- C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\dojo-webpack-plugin\lib\DojoAMDDependencyTemplateMixin.js
- C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\dojo-webpack-plugin\lib\DojoAMDModuleDependencyTemplateAsRequireId.js
- C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\dojo-webpack-plugin\lib\DojoAMDRequireItemDependencyBase.js
- C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\dojo-webpack-plugin\lib\DojoAMDRequireItemDependencyV4.js
- C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\dojo-webpack-plugin\lib\DojoAMDRequireItemDependency.js
- C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\dojo-webpack-plugin\lib\DojoAMDPlugin.js
- C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\dojo-webpack-plugin\index.js
- C:\Github\AuditCase\nl.c2c.ac.resources\web\webpack.common.js
- C:\Github\AuditCase\nl.c2c.ac.resources\web\webpack.dev.js
- C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\webpack-cli\lib\groups\ConfigGroup.js
- C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\webpack-cli\lib\webpack-cli.js
- C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\webpack-cli\lib\bootstrap.js
- C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\webpack-cli\bin\cli.js
- C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\webpack\bin\webpack.js
[webpack-cli] Error: Cannot find module 'webpack/lib/dependencies/WebpackMissingModule'
Require stack:
- C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\dojo-webpack-plugin\lib\DojoAMDDependencyTemplateMixin.js
- C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\dojo-webpack-plugin\lib\DojoAMDModuleDependencyTemplateAsRequireId.js
- C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\dojo-webpack-plugin\lib\DojoAMDRequireItemDependencyBase.js
- C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\dojo-webpack-plugin\lib\DojoAMDRequireItemDependencyV4.js
- C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\dojo-webpack-plugin\lib\DojoAMDRequireItemDependency.js
- C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\dojo-webpack-plugin\lib\DojoAMDPlugin.js
- C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\dojo-webpack-plugin\index.js
- C:\Github\AuditCase\nl.c2c.ac.resources\web\webpack.common.js
- C:\Github\AuditCase\nl.c2c.ac.resources\web\webpack.dev.js
- C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\webpack-cli\lib\groups\ConfigGroup.js
- C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\webpack-cli\lib\webpack-cli.js
- C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\webpack-cli\lib\bootstrap.js
- C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\webpack-cli\bin\cli.js
- C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\webpack\bin\webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\dojo-webpack-plugin\lib\DojoAMDDependencyTemplateMixin.js:16:30)
    at Module._compile (C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\v8-compile-cache\v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
```

**Comment by chuckdumont** [comment]
Webpack 5 is a major upgrade that breaks compatibility with existing plugins in a number of ways.  Upgrading dojo-webpack-plugin to support Webpack 5 will take some time, especially since I don't have a lot of spare time to work on this at the moment.

**Comment by fkranenburg** [comment]
We are in the process of a complete rewrite to Vue and replacing Dojo v1 will take a few years for us to complete. Hopefully we can ditch Webpack and Dojo all together and use Rollup or Vite as our main bundler. But Webpack support is important for us right now.

**Comment by ylavoie** [comment]
Exact same case for us, we are slowly moving from Dojo 1 to Vue. The planning is similar.
And we join our voice for the excellent work done by @chuckdumont on the webpack4 version!

**Comment by chuckdumont** [comment]
Version 3.0.0 has been published to npm.  This version supports webpack 5.
