### ISSUE TITLE
SyntaxError: Unexpected token '.'  after upgrading to Webpack 5

### ISSUE THREAD

**Issue by ferrykranenburgcw** [OpenNTF/dojo-webpack-plugin#338]
After upgrading to Webpack 5 I started to see this error while starting the `serve` of Webpack. It looks like it does not like the optional chaining here. I already tried to set the `target` of Webpack and `tsconfig.json` to `es2020` but that didn't work.

Is there a way to fix this?

```
[webpack-cli] C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\dojo-webpack-plugin\lib\DojoAMDResolverPlugin.js:45
                        (request.context?.originalRequest || request.request).split('!').pop(),
                                         ^

SyntaxError: Unexpected token '.'
    at new Script (vm.js:88:7)
    at NativeCompileCache._moduleCompile (C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\v8-compile-cache\v8-compile-cache.js:240:18)
    at Module._compile (C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\v8-compile-cache\v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at DojoAMDPlugin.newResolverPlugin (C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\dojo-webpack-plugin\lib\DojoAMDPlugin.js:185:33)
    at DojoAMDPlugin.apply (C:\Github\AuditCase\nl.c2c.ac.resources\web\node_modules\dojo-webpack-plugin\lib\DojoAMDPlugin.js:51:25)
```

**Comment by ferrykranenburgcw** [comment]
Upgrading to Node v14 fixes the issue.
