### ISSUE TITLE
Mac webpack build error using dojo-webpack-plugin@3.0.2 DojoAMDResolverPlugin.js

### ISSUE THREAD

**Issue by g2nconnell** [OpenNTF/dojo-webpack-plugin#345]
Using the latest dojo-webpack-plugin@3.0.2, On Windows 10, all builds fine but, on Mac I get build error in
dojo-webpack-plugin/lib/DojoAMDResolverPlugin.js:
Webpack bundling...
03 08 2021 18:37:46.841:ERROR [karma-server]: Error during file loading or preprocessing
/Users/gconnell/github/cloudCenter/web-client-application/node_modules/dojo-webpack-plugin/lib/DojoAMDResolverPlugin.js:45
			(request.context?.originalRequest || request.request).split('!').pop(),
			                 ^

SyntaxError: Unexpected token '.'
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at DojoAMDPlugin.newResolverPlugin (/Users/gconnell/github/cloudCenter/web-client-application/node_modules/dojo-webpack-plugin/lib/DojoAMDPlugin.js:185:33)
    at DojoAMDPlugin.apply (/Users/gconnell/github/cloudCenter/web-client-application/node_modules/dojo-webpack-plugin/lib/DojoAMDPlugin.js:51:25)
    at createCompiler (/Users/gconnell/github/cloudCenter/web-client-application/node_modules/webpack/lib/webpack.js:71:12)
    at create (/Users/gconnell/github/cloudCenter/web-client-application/node_modules/webpack/lib/webpack.js:118:16)
Chrome Headless 91.0.4472.114 (Mac OS 10.15.3) ERROR

**Comment by chuckdumont** [comment]
Upgrade your Node.

**Comment by g2nconnell** [comment]
Thank you.  You are right.  I was using Node 12.x.  I'm now using 14.15.4 and all works fine on both platforms.
